# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spot The Spy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spot The Spy

  pod 'IQKeyboardManager'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'SnapKit', '~> 5.6.0'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'

end
